name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: unsuitable001/buildozer3:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Install needed Android packages
      run: |
        sdkmanager "platform-tools" "platforms;android-31" "ndk;21.4.7075529"

    - name: Build debug APK
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: Таблица-Умножения-APK
        path: bin/*.apk
