name: 📱 Build Kivy APK

# даём раннеру права на чтение содержимого репо и на загрузку "actions"
permissions:
  contents: read
  actions: read

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip python3-virtualenv git \
            openjdk-8-jdk unzip \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev

      - name: Setup Python & Buildozer
        run: |
          python3 -m virtualenv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK (debug)
        run: |
          source .venv/bin/activate
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-kivy-app-apk
          path: bin/*.apk




