name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system deps
        run: |
          apt-get update && \
          apt-get install -y git zip openjdk-8-jdk

      - name: Build APK
        run: buildozer android debug --verbose

      - name: List output
        run: ls -lh bin/

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk

