# .github/workflows/android.yml
name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git zip openjdk-8-jdk

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK & NDK
        run: |
          sdkmanager "platform-tools" "platforms;android-31" "ndk;21.4.7075529"

      - name: Build APK
        run: buildozer android debug --verbose

      - name: List output
        run: ls -lh bin/

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Таблица-умножения-debug
          path: bin/*.apk


